apiVersion: v1
kind: ConfigMap
metadata:
  name: image-policy-crds
  namespace: ibm-system
  labels:
    app: {{ template "cise.name" . }}
    chart: {{ template "cise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  custom-resource-definitions.yaml: |-
    {{- include "crds.yaml.tpl" . | indent 4}}
