// Copyright 2021 Portieris Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

# This is an example configuration to enable detect-secrets in the pre-commit hook.
# Add this file to the root folder of your repository.
#
# For more information about the structure of the `config.yaml` file and how `git pre-commit` invokes each hook, read the pre-commit hook framework: https://pre-commit.com/
#
# This line indicates the use of the hook from `ibm/detect-secrets` to run the scan during the committing phase.
# When merged, `Whitewater/whitewater-detect-secrets` syncs the code to `ibm/detect-secrets`.
- repo: https://github.com/ibm/detect-secrets
  # If you want to use a specific version of detect-secrets, you can replace `master` with other git revisions such as branch, tag, or commit sha.
  # Use static references such as tags, instead of the branch name.
  #
  # Running "pre-commit autoupdate" automatically updates rev to the latest tag.
  rev: master
  hooks:
    - id: detect-secrets # pragma: whitelist secret
      # Add options for detect-secrets-hook binary. To list the possible options, run `detect-secrets-hook --help`.
      # To preview the scan result, run `pre-commit run detect-secrets`.
      # When you use "--baseline" without "--use-all-plugins", `pre-commit` scans with just plugins in the baseline file.
      # When you use "--baseline" with "--use-all-plugins", `pre-commit` scans with all available plug-ins.
      # Add "--fail-on-non-audited" to `fail pre-commit` for unaudited potential secrets.
      args: [--baseline, .secrets.baseline, --use-all-plugins ]
