[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  version = "kubernetes-1.12.2"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.12.2"
  name = "k8s.io/client-go"

[[constraint]]
  version = "kubernetes-1.12.2"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  version = "kubernetes-1.12.2"
  name = "k8s.io/apimachinery"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true
