apiVersion: v1
kind: ConfigMap
metadata:
  name: armada-image-policies
  namespace: ibm-system
  labels:
    app: {{ template "cise.name" . }}
    chart: {{ template "cise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  armada-custom-resources.yaml: |-
    {{- include "policies.yaml.tpl" . | indent 4}}
