apiVersion: batch/v1
kind: Job
metadata:
  name: create-armada-image-policies
  namespace: ibm-system
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-3"
  labels:
    app: {{ template "cise.name" . }}
    chart: {{ template "cise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: create-crds
      labels:
        app: {{ template "cise.name" . }}
        chart: {{ template "cise.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: ibmcloud-image-enforcement
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command:
            - /kubectl
            - apply
            - -f
            - /tmp/scanner/armada-custom-resources.yaml
          volumeMounts:
            - mountPath: "/tmp/scanner"
              name: tmp-configmap-scanner
      volumes:
        - name: tmp-configmap-scanner
          configMap:
            name: armada-image-policies
      restartPolicy: OnFailure
      