---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    securityenforcement.admission.cloud.ibm.com/namespace: skip
