apiVersion: v1
kind: Service
metadata:
  name: {{ template "portieris.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "portieris.name" . }}
  {{- if .Values.selectByRelease }}
    release: {{ .Release.Name }}
  {{ end }}