apiVersion: batch/v1
kind: Job
metadata:
  name: delete-admission-webhooks
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: delete-admission-webhooks
      labels:
        app: {{ template "portieris.name" . }}
        chart: {{ template "portieris.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: portieris
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command:
            - /kubectl
            - delete
            - MutatingWebhookConfiguration
            - image-admission-config
            - --ignore-not-found=true
      restartPolicy: OnFailure
