apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: any
spec:
   repositories:
    - name: "*"
      policy:
        simple:
          requirements:
          - type: "insecureAcceptAnything"
