apiVersion: portieris.cloud.ibm.com/v1
kind: ImagePolicy
metadata:
  name: any
spec:
   repositories:
    - name: "empty"
    - name: "otherEmpty"
      policy:
    - name: "foo"
      policy:
        simple:
          requirements:
          - type: "insecureAcceptAnything"
    - name: "icr.io/cise/*"
      policy:
        simple:
          requirements:
          - type: "signedBy"
            keySecret: simple1pubkey
          - type: "signedBy"
            keySecret: simple2pubkey
        vulnerability:
          ICCRVA:
            enabled: true
    - name: "icr.io/cise/*"
      policy:
         simple:
           requirements:
           - type: "signedBy"
             keySecret: simple1pubkey
             signedIdentity:
                type: "remapIdentity"
                prefix: "icr.io/cise/remap"
                signedPrefix: "icr.io/cise"
    - name: "icr.io/cise/*"
      policy:
         simpleStore:
            url: "https://foo.com/x"
            auth: storesecret 
         simple:
           requirements:
           - type: "signedBy"
             keySecret: simple1pubkey