apiVersion: v1
kind: ConfigMap
metadata:
  name: admission-webhooks
  namespace: ibm-system
  labels:
    app: {{ template "cise.name" . }}
    chart: {{ template "cise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  webhooks.yaml: |-
    {{- include "webhooks.yaml.tpl" . | indent 4}}
